// <auto-generated />
using Agencia.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Agencia.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240201193637_firstmigration")]
    partial class firstmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Agencia.Model.Destino", b =>
                {
                    b.Property<int>("DestinoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("descricao");

                    b.Property<string>("DestinoURL")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("DestinoURL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nome");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("preco");

                    b.HasKey("DestinoId");

                    b.ToTable("Destinos");

                    b.HasData(
                        new
                        {
                            DestinoId = 1,
                            Descricao = "Cidade maravilhosa com praias incríveis",
                            DestinoURL = "https://images.pexels.com/photos/2868240/pexels-photo-2868240.jpeg",
                            Nome = "Rio de Janeiro",
                            Preco = 1500.00m
                        },
                        new
                        {
                            DestinoId = 2,
                            Descricao = "Maior cidade do Brasil, centro financeiro",
                            DestinoURL = "https://images.pexels.com/photos/2065850/pexels-photo-2065850.jpeg",
                            Nome = "São Paulo",
                            Preco = 1200.00m
                        },
                        new
                        {
                            DestinoId = 3,
                            Descricao = "Estado com rica história e belas paisagens",
                            DestinoURL = "https://destinosnotaveis.com.br/wp-content/uploads/2023/05/Mariana-MG.jpg",
                            Nome = "Minas Gerais",
                            Preco = 1000.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
